Repository BongManYoung/Backend, pull requests merged in 2021-11, with the labels that each got.

#1 Add review entity
  src/main/generated/com/hackathon/MYD/model/review/QReviewEntity.java
  src/main/java/com/hackathon/MYD/model/review/ReviewEntity.java
Labels: enhancement

#3 Hotfix
  .gitignore
Labels: bug

#4 Delete querydsl config
  build.gradle
Labels: bug, documentation

#5 Feature/join
  .gitignore
  build.gradle
  src/main/java/com/hackathon/MYD/config/WebConfig.java
  src/main/java/com/hackathon/MYD/model/controller/AuthController.java
  src/main/java/com/hackathon/MYD/model/repository/UserRepository.java
  src/main/java/com/hackathon/MYD/model/service/AuthService.java
  src/main/java/com/hackathon/MYD/model/user/SingUpRequest.java
  src/main/java/com/hackathon/MYD/model/user/UserEntity.java
Labels: enhancement

#7 Feature/identifier review
  src/main/java/com/hackathon/MYD/model/empathy/EmpathyEntity.java
  src/main/java/com/hackathon/MYD/model/empathy/repository/EmpathyRepository.java
  src/main/java/com/hackathon/MYD/model/review/ReviewEntity.java
  src/main/java/com/hackathon/MYD/model/review/repository/ReviewRepository.java
  src/main/java/com/hackathon/MYD/model/user/UserEntity.java
Labels: enhancement

#8 Feature/login
  build.gradle
  src/main/java/com/hackathon/MYD/exception/BasicException.java
  src/main/java/com/hackathon/MYD/exception/BasicExceptionHandler.java
  src/main/java/com/hackathon/MYD/exception/ExceptionMessage.java
  src/main/java/com/hackathon/MYD/exception/ExceptionResponse.java
  src/main/java/com/hackathon/MYD/exception/UserNicknameUniqueExceptionHandler.java
  src/main/java/com/hackathon/MYD/model/controller/AuthController.java
  src/main/java/com/hackathon/MYD/model/user/UserEntity.java
  src/main/java/com/hackathon/MYD/model/user/controller/AuthController.java
  src/main/java/com/hackathon/MYD/model/user/payload/request/SingInRequest.java
  src/main/java/com/hackathon/MYD/model/user/payload/request/SingUpRequest.java
  src/main/java/com/hackathon/MYD/model/user/payload/response/TokenResponse.java
  src/main/java/com/hackathon/MYD/model/user/repository/UserRepository.java
  src/main/java/com/hackathon/MYD/model/user/service/AuthService.java
  src/main/java/com/hackathon/MYD/util/JwtUtil.java
  src/main/resources/application.yml
Labels: enhancement

#9 Add 연관관게 복잡도 증가로 인해 단일 테이블 전략으로 바꿈
  src/main/java/com/hackathon/MYD/model/empathy/EmpathyEntity.java
  src/main/java/com/hackathon/MYD/model/empathy/repository/EmpathyRepository.java
  src/main/java/com/hackathon/MYD/model/review/ReviewEntity.java
Labels: documentation

#15 Feature/review
  src/main/java/com/hackathon/MYD/model/review/ReviewEntity.java
  src/main/java/com/hackathon/MYD/model/review/controller/ReviewController.java
  src/main/java/com/hackathon/MYD/model/review/dto/ReviewDto.java
  src/main/java/com/hackathon/MYD/model/review/repository/ReviewRepository.java
  src/main/java/com/hackathon/MYD/model/review/repository/ReviewSummary.java
  src/main/java/com/hackathon/MYD/model/review/service/ReviewService.java
  src/main/java/com/hackathon/MYD/model/store/repository/StoreRepository.java
  src/main/resources/application.yml
Labels: enhancement

#17 Update webConfig allowedOrigins
  src/main/java/com/hackathon/MYD/config/WebConfig.java
Labels: bug
